### PR TITLE
Create trans_blq to enhance censored data presentation

### PR DESCRIPTION
**Pull request by billdenney**
I needed a graph to better represent BLQ data today.  I thought that this trans could be helpful (see `?blq_trans` for how to use it).  If you don't think that it is a good fit, let me know, and I will try to find a better home.

### CODE REVIEW

**Comment by mattfidler** [comment]
I'm unsure what this does, but I did create something similar a `geom_cens()` for `ggplot2`

**Comment by mattfidler** [comment]
Reading the code, it is different the `geom_cens()` which visualizes the lloq assumptions under monolix/nlmixr.

**Comment by billdenney** [comment]
At a quick look, I think that it is complimentary to `geom_cens()`.  I did a very cursory look at `geom_cens()`, and that shows the data differently when it is BLQ.  This is more for scaling and changing axis limits.

It would be good to make these work together better.  (So this PR should not be merged until that is done or at least better evaluated.)  That said, `nlmixr` would be a heavy dependency if I'm doing exploratory data analysis and want to illustrate the BLQ data.  @mattfidler, any interest in moving `geom_cens()` to another package (possibly this one if @kestrel99 agrees) where it could be part of a lighter dependency.

**Comment by mattfidler** [comment]
I initially thought of putting the `geom_cens` in `xgxr`, and even discussed it with the team.  I eventually decided against it because I need the function for the censoring support, which would require an Import instead of Suggests. 

I agree that `nlmixr` is a heavy dependency. I could move it to `RxODE` without loosing much,  though that is also a heavy dependency.  It also seems a bit out of place in `RxODE` since it only applies when modelling data.

However, `nlmixr` will not be as heavy as it used to be without python.

**Comment by kestrel99** [comment]
Is it worth creating a separate, independent package that rolls up the censoring functionality? I agree nlmixr is a gigantic dependency to have.

**Comment by mattfidler** [comment]
Adding a new package adds another package to the Imports too, I might as well ask for `xgxr` to reconsider.  However, `xgxr` may drift or another package may drift and not support the small things that `nlmixr` needs.  

I am willing to move them (that is `geom_cens()` and `geom_amt()`) to `RxODE` and you could use conditionally as a Suggests package.

**Comment by mattfidler** [comment]
I added the semi-`log` scales initially to `xgxr` and they drifted some which is perfectly reasonable; At the same time, I don't want to add more work to my plate to maintain the comparability with another package.

**Comment by mattfidler** [comment]
This has been moved to `RxODE`

**Pull request merged**
